# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bfffdf8c05c6c05eedf8ba98c654ca7f351d7e511aa953142863f718c29f399f5483306250cac529c62aeab2890ced24b7803b1ae6682b2638deef39247a5c2f

test:
  secret_key_base: 7c1afaf0fd05bea19cc232424afc570767735e5c11b41b9713cd80f6aa9aa0764a21fcabd77212df2db1d8363d18287b6bc900ed1576716dbd86f45c2cac6697

production:
  secret_key_base: 6751bbaaa4ca172bbb77f2ef758f3bb669489d660df05260e385377e8ae7d333a58d4dc79a1e7d7dd05bfbca86d3dd1927f84d13d73257fe1e0ce9ab94391647
